CLEAR SCREEN;
CLEAR COLUMNS;
CLEAR BREAK;
CLEAR COMPUTE; 

SET VERIFY OFF
SET LINESIZE 70
SET PAGESIZE 150
SET NEWPAGE NONE
SET UNDERLINE =
SET COLSEP '| '
SET FEEDBACK OFF

ACCEPT ALBARAN PROMPT 'Introducir el codigo de albaran (ALB-XXX): '

TTITLE LEFT ''-
SKIP 2 RIGHT 'INSERT CONIS GAMES'-
SKIP 1 RIGHT 'CIF: G-32147857'-
SKIP 2 RIGHT 'C/ AFRODITA, 785'-
SKIP 1 RIGHT '45270, MOCEJON (TOLEDO)'-
SKIP 1 RIGHT 'TEL: 925547874'-

COLUMN N_ALBARAN HEADING 'ALBARAN' FORMAT A8
COLUMN FECHA HEADING 'FECHA'
COLUMN NOMBRE, APELLIDO HEADING 'CLIENTE' FORMAT A42
COLUMN DIRECCION HEADING 'DIRECCION'
COLUMN TEL HEADING 'TELEFONO' FORMAT A10
COLUMN N_PRODUCTO HEADING 'PRODUCTO' FORMAT A35
COLUMN CANTIDAD HEADING 'CANTIDAD'
COLUMN CANTIDAD JUS C

SELECT N_ALBARAN, FECHA 
FROM REGISTRO_ALBARAN
WHERE UPPER(N_ALBARAN) 
LIKE UPPER('&ALBARAN')
ORDER BY N_ALBARAN;
	
TTITLE OFF
	
SELECT NOMBRE, APELLIDO 
FROM CLIENTE C, REGISTRO_PEDIDO P, REGISTRO_ALBARAN A
WHERE UPPER(N_ALBARAN) 
LIKE UPPER('&ALBARAN')
AND C.DNI = P.DNI
AND P.N_PEDIDO = A.N_PEDIDO;
		
SELECT C.DIRECCION, C.TEL 
FROM CLIENTE C, REGISTRO_PEDIDO P, REGISTRO_ALBARAN A
WHERE UPPER(N_ALBARAN) 
LIKE UPPER('&ALBARAN')
AND C.DNI = P.DNI
AND P.N_PEDIDO = A.N_PEDIDO;
		
SELECT P.N_PRODUCTO, L.CANTIDAD, CONCAT(TO_CHAR(P.PRECIO, '999G999D99'), ' Euros') "PRECIO UNITARIO" 
FROM PRODUCTO P, LINEA_ALBARAN L
WHERE UPPER(L.N_ALBARAN) 
LIKE UPPER('&ALBARAN')
AND P.C_PRODUCTO = L.C_PRODUCTO
ORDER BY L.N_LINEA_A;
	
COLUMN REGISTRO_ALBARAN NEW_VALUE REGISTRO_ALBARAN
COLUMN REGISTRO_ALBARAN NOPRINT
SELECT 'ALBARAN_' REGISTRO_ALBARAN FROM DUAL;

COLUMN FECHA NEW_VALUE FECHA
COLUMN FECHA NOPRINT
SELECT TO_CHAR(SYSDATE,'YYYYMMDD_HH24MISS') FECHA FROM DUAL;

