CLEAR SCREEN;
CLEAR COLUMNS;
CLEAR BREAK;
CLEAR COMPUTE; 

SET VERIFY OFF
SET LINESIZE 120
SET PAGESIZE 250
SET NEWPAGE NONE
SET UNDERLINE =
SET COLSEP '| '
SET FEEDBACK OFF

ACCEPT FACTURA PROMPT 'Introducir el numero de factura (FAC-XXX): '

TTITLE LEFT ''-
SKIP 2 RIGHT 'INSERT CONIS GAMES'-
SKIP 1 RIGHT 'CIF: G-32147857'-
SKIP 2 RIGHT 'C/ AFRODITA, 785'-
SKIP 1 RIGHT '45270, MOCEJON (TOLEDO)'-
SKIP 1 RIGHT 'TEL: 925547874'-

BREAK ON REPORT SKIP
COMPUTE SUM LABEL 'TOTAL GENERAL' OF 'TOTAL' ON REPORT
COMPUTE SUM OF 'TOTAL CON IVA' ON REPORT

COLUMN N_FACTURA HEADING 'FACTURA' FORMAT A8
COLUMN N_ALBARAN HEADING 'ALBARAN' FORMAT A8
COLUMN FECHA HEADING 'FECHA FACTURA'

COLUMN NOMBRE, APELLIDO HEADING 'Cliente' FORMAT A42

COLUMN DIRECCION HEADING 'Direccion'
COLUMN TEL HEADING 'NUM' FORMAT A10

COLUMN N_PRODUCTO HEADING 'Productos' FORMAT A40
COLUMN VAL_IVA HEADING '% IVA' 
COLUMN CANTIDAD HEADING 'Cantidad'
COLUMN CANTIDAD JUS C
COLUMN PRECIO HEADING 'Precio' FORMAT A15

TTITLE OFF

SELECT RF.N_FACTURA, RA.N_ALBARAN, RF.FECHA 
FROM REGISTRO_FACTURA RF, REGISTRO_ALBARAN RA
WHERE UPPER(RF.N_FACTURA)
LIKE UPPER('&FACTURA')
AND RF.N_FACTURA = RA.N_FACTURA
ORDER BY RF.N_FACTURA;

SELECT DISTINCT C.NOMBRE, C.APELLIDO 
FROM CLIENTE C, REGISTRO_PEDIDO RP, REGISTRO_ALBARAN RA, REGISTRO_FACTURA RF
WHERE UPPER(RF.N_FACTURA) 
LIKE UPPER('&FACTURA')
AND C.DNI = RP.DNI
AND RP.N_PEDIDO = RA.N_PEDIDO
AND RA.N_FACTURA = RF.N_FACTURA;

SELECT DISTINCT C.DIRECCION, C.TEL 
FROM CLIENTE C, REGISTRO_PEDIDO RP, REGISTRO_ALBARAN RA, REGISTRO_FACTURA RF
WHERE UPPER(RF.N_FACTURA) 
LIKE UPPER('&FACTURA')
AND C.DNI = RP.DNI
AND RP.N_PEDIDO = RA.N_PEDIDO
AND RF.N_FACTURA = RA.N_FACTURA;


SELECT DISTINCT P.N_PRODUCTO, I.VAL_IVA, LA.CANTIDAD, 
				TO_CHAR(P.PRECIO, '999G999D99') "PRECIO",
				ROUND((P.PRECIO * LA.CANTIDAD), 2) "TOTAL",
				ROUND(((P.PRECIO * LA.CANTIDAD) * I.VAL_IVA), 2) "TOTAL CON IVA"
FROM IVA I, PRODUCTO P, LINEA_ALBARAN LA, REGISTRO_FACTURA RF, 
	 REGISTRO_ALBARAN RA, REGISTRO_PEDIDO RP, CLIENTE C
WHERE UPPER(RF.N_FACTURA) 
LIKE UPPER('&FACTURA')
AND I.IVA = P.IVA
AND P.C_PRODUCTO = LA.C_PRODUCTO
AND RF.N_FACTURA = RA.N_FACTURA
AND RA.N_ALBARAN = LA.N_ALBARAN
AND RP.N_PEDIDO = RA.N_PEDIDO
AND C.DNI = RP.DNI;

COLUMN REGISTRO_FACTURA NEW_VALUE REGISTRO_FACTURA
COLUMN REGISTRO_FACTURA NOPRINT
SELECT 'FACTURA_' REGISTRO_FACTURA FROM DUAL;


