CLEAR SCREEN;
CLEAR COLUMNS;
CLEAR BREAK;
CLEAR COMPUTE; 

SET VERIFY OFF
SET LINESIZE 80
SET PAGESIZE 60
SET NEWPAGE NONE
SET UNDERLINE _
SET FEEDBACK OFF

TTITLE LEFT '+++++++++++++++++++++++++++'-
SKIP 1 LEFT '[ INVENTARIO DE PRODUCTOS ]'-
SKIP 1 LEFT '+++++++++++++++++++++++++++'-
SKIP 2

COLUMN C_PRODUCTO FORMAT A7
COLUMN C_PRODUCTO HEADING 'CODIGO'
COLUMN N_PRODUCTO FORMAT A35
COLUMN N_PRODUCTO HEADING 'NOMBRE'
COLUMN PRECIO HEADING 'PRECIO'
COLUMN R.IVA_POR HEADING 'IVA'

BTITLE LEFT '  '-
SKIP 2

SELECT C_PRODUCTO, N_PRODUCTO, CONCAT(TO_CHAR(PRECIO, '999G999D99'), ' Euros') "Precio" 
FROM PRODUCTO P
ORDER BY C_PRODUCTO;

TTITLE OFF
BTITLE OFF








