CLEAR SCREEN;
CLEAR COLUMNS;
CLEAR BREAK;
CLEAR COMPUTE; 

SET VERIFY OFF
SET LINESIZE 90
SET PAGESIZE 150
SET NEWPAGE NONE
SET UNDERLINE =
SET COLSEP '| '
SET FEEDBACK OFF

ACCEPT PEDIDO PROMPT 'Introducir el codigo de pedido (PED-XXX): '

TTITLE LEFT ''-
SKIP 2 RIGHT 'INSERT CONIS GAMES'-
SKIP 1 RIGHT 'CIF: G-32147857'-
SKIP 2 RIGHT 'C/ AFRODITA, 785'-
SKIP 1 RIGHT '45270, MOCEJON (TOLEDO)'-
SKIP 1 RIGHT 'TEL: 925547874'-

COLUMN N_PEDIDO HEADING 'PEDIDO' FORMAT A10
COLUMN FECHA HEADING 'FECHA'
SKIP 1
COLUMN NOMBRE, APELLIDO HEADING 'CLIENTE' FORMAT A42
SKIP 1
COLUMN DIRECCION HEADING 'DIRECCION'
COLUMN TEL HEADING 'TELEFONO' FORMAT A10
SKIP 1
COLUMN N_PRODUCTO HEADING 'PRODUCTO' FORMAT A35
COLUMN CANTIDAD HEADING 'CANTIDAD'
COLUMN CANTIDAD JUS C
COLUMN PRECIO HEADING 'PRECIO UNITARIO'

SELECT N_PEDIDO, FECHA 
FROM REGISTRO_PEDIDO
WHERE UPPER(N_PEDIDO) 
LIKE UPPER('&PEDIDO')
ORDER BY N_PEDIDO;
	
TTITLE OFF

SELECT NOMBRE, APELLIDO FROM CLIENTE C, REGISTRO_PEDIDO R
WHERE UPPER(N_PEDIDO) 
LIKE UPPER('&PEDIDO')
AND C.DNI = R.DNI;

SELECT DIRECCION, TEL 
FROM CLIENTE C, REGISTRO_PEDIDO R
WHERE UPPER(N_PEDIDO) 
LIKE UPPER('&PEDIDO')
AND C.DNI = R.DNI;
		
SELECT P.N_PRODUCTO, L.CANTIDAD, CONCAT(TO_CHAR(P.PRECIO, '999G999D99'), ' Euros') "PRECIO UNITARIO" 
FROM PRODUCTO P, LINEA_PEDIDO L
WHERE UPPER(N_PEDIDO) 
LIKE UPPER('&PEDIDO')
AND P.C_PRODUCTO = L.C_PRODUCTO
ORDER BY L.N_LINEA_P;

COLUMN REGISTRO_PEDIDO NEW_VALUE REGISTRO_PEDIDO
COLUMN REGISTRO_PEDIDO NOPRINT
SELECT 'PEDIDO_' REGISTRO_PEDIDO FROM DUAL;

COLUMN FECHA NEW_VALUE FECHA
COLUMN FECHA NOPRINT
SELECT TO_CHAR(SYSDATE,'YYYYMMDD_HH24MISS') FECHA FROM DUAL;

