CLEAR SCREEN;
CLEAR COLUMNS;
CLEAR BREAK;
CLEAR COMPUTE;

SET VERIFY OFF
SET LINESIZE 70
SET NEWPAGE NONE
SET UNDERLINE =
SET COLSEP ' '

ACCEPT ALBARAN PROMPT 'INTRODUZCA EL NUMERO DE ALBARAN (XXX-A): '

SPOOL "Z:\1DAW\BBDD\PROYECTO\SPOOLS\&CAB_ALB&FECHA_ARCH" APPEND

TTITLE LEFT ''-
SKIP 1 RIGHT 'CIF: G36667483'-
SKIP 2 RIGHT 'ALIMENTACION CHEN'-
SKIP 1 RIGHT 'CALLE DE LAS CAMELIAS, 25'-
SKIP 1 RIGHT '28047, MADRID'-

COLUMN N_ALB HEADING 'ALBARAN' FORMAT A8
COLUMN FECHA_ALB HEADING 'FECHA'

COLUMN NOM_CLI HEADING 'CLIENTE' FORMAT A42

COLUMN CALLE HEADING 'DIRECCION'
COLUMN NUM HEADING 'NUM' FORMAT A3
COLUMN CP HEADING 'CP'
COLUMN CP JUS C
COLUMN PROV HEADING 'PROVINCIA' FORMAT A10
COLUMN CCAA HEADING 'CCAA' FORMAT A10
COLUMN CCAA JUS C

COLUMN NOM_PROD HEADING 'PRODUCTO' FORMAT A15
COLUMN CANT HEADING 'CANTIDAD'
COLUMN CANT JUS C

SELECT N_ALB, FECHA_ALB FROM CAB_ALB
	WHERE UPPER(N_ALB) LIKE UPPER('&ALBARAN')
	ORDER BY N_ALB;
	
TTITLE OFF
	
SELECT NOM_CLI FROM CLIENTE C, CAB_PED P, CAB_ALB A
	WHERE UPPER(N_ALB) LIKE UPPER('&ALBARAN')
		AND C.DNI = P.DNI
		AND P.N_PED = A.N_PED;
		
SELECT C.CALLE, C.NUM, C.CP, C.PROV, C.CCAA FROM CLIENTE C, CAB_PED P, CAB_ALB A
	WHERE UPPER(N_ALB) LIKE UPPER('&ALBARAN')
		AND C.DNI = P.DNI
		AND P.N_PED = A.N_PED;
		
SELECT P.NOM_PROD, L.CANT, CONCAT(TO_CHAR(P.PRECIO, '99990.99'), ' EUROS') "PRECIO UNITARIO" FROM PRODUCTO P, LIN_ALB L
	WHERE UPPER(L.N_ALB) LIKE UPPER('&ALBARAN')
		AND P.COD_PROD = L.COD_PROD
	ORDER BY L.N_LIN;
	
COLUMN CAB_ALB NEW_VALUE CAB_ALB
COLUMN CAB_ALB NOPRINT
SELECT 'ALBARAN_' CAB_ALB FROM DUAL;

COLUMN FECHA_ARCH NEW_VALUE FECHA_ARCH
COLUMN FECHA_ARCH NOPRINT
SELECT TO_CHAR(SYSDATE,'YYYYMMDD_HH24MISS') FECHA_ARCH FROM DUAL;

SPOOL OFF