CLEAR SCREEN;
CLEAR COLUMNS;
CLEAR BREAK;
CLEAR COMPUTE;

SET VERIFY OFF
SET LINESIZE 70
SET NEWPAGE NONE
SET UNDERLINE =
SET COLSEP ' '

ACCEPT FACTURA PROMPT 'INTRODUZCA EL NUMERO DE FACTURA (XXX-F): '

SPOOL "Z:\1DAW\BBDD\PROYECTO\SPOOLS\&CAB_FACT&FECHA_ARCH" APPEND

TTITLE LEFT ''-
SKIP 1 RIGHT 'CIF: G36667483'-
SKIP 2 RIGHT 'ALIMENTACION CHEN'-
SKIP 1 RIGHT 'CALLE DE LAS CAMELIAS, 25'-
SKIP 1 RIGHT '28047, MADRID'-

BREAK ON REPORT SKIP
COMPUTE SUM LABEL 'TOTAL GENERAL' OF 'TOTAL' ON REPORT
COMPUTE SUM OF 'TOTAL CON IVA' ON REPORT

COLUMN N_FACT HEADING 'FACTURA' FORMAT A8
COLUMN N_ALB HEADING 'ALBARAN' FORMAT A8
COLUMN FECHA_FACT HEADING 'FECHA FACTURA'

COLUMN NOM_CLI HEADING 'CLIENTE' FORMAT A42

COLUMN CALLE HEADING 'DIRECCION'
COLUMN NUM HEADING 'NUM' FORMAT A3
COLUMN CP HEADING 'CP'
COLUMN CP JUS C
COLUMN PROV HEADING 'PROVINCIA' FORMAT A10
COLUMN CCAA HEADING 'CCAA' FORMAT A10
COLUMN CCAA JUS C

COLUMN NOM_PROD HEADING 'PRODUCTOS' FORMAT A15
COLUMN IVA_POR HEADING '% IVA' FORMAT A6

COLUMN CANT HEADING 'CANTIDAD'
COLUMN CANT JUS C
COLUMN PRECIO HEADING 'PRECIO' FORMAT A7

SELECT CF.N_FACT, CA.N_ALB, FECHA_FACT FROM CAB_FACT CF, CAB_ALB CA
	WHERE UPPER(CF.N_FACT) LIKE UPPER('&FACTURA')
		AND CF.N_FACT = CA.N_FACT
	ORDER BY CF.N_FACT;

TTITLE OFF

SELECT DISTINCT C.NOM_CLI FROM CLIENTE C, CAB_PED CP, CAB_ALB CA, CAB_FACT CF
	WHERE UPPER(CF.N_FACT) LIKE UPPER('&FACTURA')
		AND C.DNI = CP.DNI
		AND CP.N_PED = CA.N_PED
		AND CA.N_FACT = CF.N_FACT;
		
SELECT DISTINCT C.CALLE, C.NUM, C.CP, C.PROV, C.CCAA FROM CLIENTE C, CAB_PED CP, CAB_ALB CA, CAB_FACT CF
	WHERE UPPER(CF.N_FACT) LIKE UPPER('&FACTURA')
		AND C.DNI = CP.DNI
		AND CP.N_PED = CA.N_PED
		AND CF.N_FACT = CA.N_FACT;
		
SELECT DISTINCT P.NOM_PROD,I.IVA_POR, LA.CANT, 
				TO_CHAR(P.PRECIO, '990.99') "PRECIO",
				ROUND((P.PRECIO * LA.CANT), 2) "TOTAL",
				ROUND(((P.PRECIO * LA.CANT) * I.IVA), 2) "TOTAL CON IVA"
FROM IVA I, PRODUCTO P, LIN_ALB LA, CAB_FACT CF, CAB_ALB CA, CAB_PED CP, CLIENTE C
	WHERE UPPER(CF.N_FACT) LIKE UPPER('&FACTURA')
		AND I.COD_IVA = P.COD_IVA
		AND P.COD_PROD = LA.COD_PROD
		AND CF.N_FACT = CA.N_FACT
		AND CA.N_ALB = LA.N_ALB
		AND CP.N_PED = CA.N_PED
		AND C.DNI = CP.DNI
	ORDER BY I.IVA_POR DESC;

COLUMN CAB_FACT NEW_VALUE CAB_FACT
COLUMN CAB_FACT NOPRINT
SELECT 'FACTURA_' CAB_FACT FROM DUAL;

COLUMN FECHA_ARCH NEW_VALUE FECHA_ARCH
COLUMN FECHA_ARCH NOPRINT
SELECT TO_CHAR(SYSDATE,'YYYYMMDD_HH24MISS') FECHA_ARCH FROM DUAL;

SPOOL OFF