CLEAR SCREEN;
CLEAR COLUMNS;
CLEAR BREAK;
CLEAR COMPUTE;

SET VERIFY OFF
SET LINESIZE 80
SET PAGESIZE 45
SET NEWPAGE NONE
SET UNDERLINE =

SPOOL "Z:\1DAW\BBDD\PROYECTO\SPOOLS\&CAB_LIST_PED&FECHA_ARCH" APPEND

TTITLE CENTER '===================='-
SKIP 1 CENTER 'LISTADO DE PRODUCTOS'-
SKIP 1 CENTER '===================='-
SKIP 2

COLUMN COD_PROD FORMAT A7
COLUMN COD_PROD HEADING 'CODIGO'
COLUMN NOM_PROD FORMAT A15
COLUMN NOM_PROD HEADING 'NOMBRE'
COLUMN PRECIO HEADING 'PRECIO'
COLUMN I.IVA_POR HEADING 'IVA'

SELECT COD_PROD, NOM_PROD, I.IVA_POR "IVA", CONCAT(TO_CHAR(PRECIO, '0.99'), ' EUROS') "PRECIO" FROM PRODUCTO P, IVA I
	WHERE P.COD_IVA = I.COD_IVA
	ORDER BY COD_PROD;
	
TTITLE OFF

COLUMN CAB_LIST_PED NEW_VALUE CAB_LIST_PED
COLUMN CAB_LIST_PED NOPRINT
SELECT 'LIST_PED_' CAB_LIST_PED FROM DUAL;

COLUMN FECHA_ARCH NEW_VALUE FECHA_ARCH
COLUMN FECHA_ARCH NOPRINT
SELECT TO_CHAR(SYSDATE,'YYYYMMDD_HH24MISS') FECHA_ARCH FROM DUAL;

SPOOL OFF