CLEAR SCREEN;
CLEAR COLUMNS;
CLEAR BREAK;
CLEAR COMPUTE;

SET VERIFY OFF
SET LINESIZE 70
SET NEWPAGE NONE
SET UNDERLINE =
SET COLSEP ' '

SPOOL "Z:\1DAW\BBDD\PROYECTO\SPOOLS\&CAB_PED&FECHA_ARCH" APPEND

ACCEPT PEDIDO PROMPT 'INTRODUZCA EL NUMERO DE PEDIDO (XX-PD): '

TTITLE LEFT ''-
SKIP 1 RIGHT 'CIF: G36667483'-
SKIP 2 RIGHT 'ALIMENTACION CHEN'-
SKIP 1 RIGHT 'CALLE DE LAS CAMELIAS, 25'-
SKIP 1 RIGHT '28047, MADRID'-

COLUMN N_PED HEADING 'PEDIDO' FORMAT A6
COLUMN FECHA_PED HEADING 'FECHA'

COLUMN NOM_CLI HEADING 'CLIENTE' FORMAT A42

COLUMN CALLE HEADING 'DIRECCION'
COLUMN NUM HEADING 'NUM' FORMAT A3
COLUMN CP HEADING 'CP'
COLUMN CP JUS C
COLUMN PROV HEADING 'PROVINCIA' FORMAT A10
COLUMN CCAA HEADING 'CCAA' FORMAT A10
COLUMN CCAA JUS C

COLUMN NOM_PROD HEADING 'PRODUCTO' FORMAT A15
COLUMN CANT HEADING 'CANTIDAD'
COLUMN CANT JUS C
COLUMN PRECIO HEADING 'PRECIO UNITARIO'

SELECT N_PED, FECHA_PED FROM CAB_PED
	WHERE UPPER(N_PED) LIKE UPPER('&PEDIDO')
	ORDER BY N_PED;
	
TTITLE OFF

SELECT NOM_CLI FROM CLIENTE C, CAB_PED P
	WHERE UPPER(N_PED) LIKE UPPER('&PEDIDO')
	AND C.DNI = P.DNI;

SELECT C.CALLE, C.NUM, C.CP, C.PROV, C.CCAA FROM CLIENTE C, CAB_PED P
	WHERE UPPER(N_PED) LIKE UPPER('&PEDIDO')
		AND C.DNI = P.DNI;
		
SELECT P.NOM_PROD, L.CANT, CONCAT(TO_CHAR(P.PRECIO, '99990.99'), ' EUROS') "PRECIO UNITARIO" FROM PRODUCTO P, LIN_PED L
	WHERE UPPER(N_PED) LIKE UPPER('&PEDIDO')
		AND P.COD_PROD = L.COD_PROD
	ORDER BY L.N_LIN;

COLUMN CAB_PED NEW_VALUE CAB_PED
COLUMN CAB_PED NOPRINT
SELECT 'PEDIDO_' CAB_PED FROM DUAL;

COLUMN FECHA_ARCH NEW_VALUE FECHA_ARCH
COLUMN FECHA_ARCH NOPRINT
SELECT TO_CHAR(SYSDATE,'YYYYMMDD_HH24MISS') FECHA_ARCH FROM DUAL;

SPOOL OFF